CODEBASE/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

// Controllers
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\VendorController;
use App\Http\Controllers\Admin\AccountController;
use App\Http\Controllers\Admin\AssessorController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ConsultantController;
use App\Http\Controllers\Admin\ApplicationController;
use App\Http\Controllers\Admin\CompanyController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', function () {
    echo 'Admin';
});

Route::any('login', [AuthController::class, 'login'])->name('login');
Route::any('forgot-password', [AuthController::class, 'forgotPassword'])->name('forgotPassword');
Route::any('forgotPassword', [AuthController::class, 'forgotPasswordPage'])->name('forgotPasswordPage');

Route::middleware(['auth:admin'])->group(function () {

    Route::any('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::any('profile', [AccountController::class, 'profile'])->name('profile');
    Route::any('change-password', [AccountController::class, 'changePassword'])->name('changePassword');
    Route::any('changePassword', [AccountController::class, 'changePasswordPage'])->name('changePasswordPage');
    Route::any('logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('assessors_data', [AssessorController::class, 'data'])->name('assessors.data');
    Route::put('assessors_bulk_update', [AssessorController::class, 'statusUpdateBlock'])->name('assessors.bulk_update');
    Route::get('assessors_bulk_export', [AssessorController::class, 'exportBlock'])->name('assessors.bulk_export');
    Route::resource('assessors', AssessorController::class);
    Route::any('nda/{id}',[AssessorController::class, 'nda'])->name('assessors.nda');
    Route::get('assessors_approve/{assessor}', [AssessorController::class, 'approve'])->name('assessors.approve');
    Route::get('remark_logs/{id}', [AssessorController::class, 'remarkLogs'])->name('assessors.logs');
    Route::any('edit/{id}', [AssessorController::class, 'addEditAssessor'])->name('assessors.addEditAssessor');


    Route::get('consultant_data', [ConsultantController::class, 'data'])->name('consultant.data');
    Route::put('consultant_bulk_update', [ConsultantController::class, 'statusUpdateBlock'])->name('consultant.bulk_update');
    Route::get('consultant_bulk_export', [ConsultantController::class, 'exportBlock'])->name('consultant.bulk_export');
    Route::resource('consultant', ConsultantController::class);
    Route::get('consultant_approve/{consultant}', [ConsultantController::class, 'approve'])->name('consultant.approve');

    Route::any('', [CompanyController::class, 'index'])->name('company.index');
    Route::resource('company', CompanyController::class);
    Route::put('status_change', [CompanyController::class, 'status_change'])->name('company.status_change');
    Route::get('company_approve/{company}', [CompanyController::class, 'approve'])->name('company.approve');
    Route::any('addCompany', [CompanyController::class, 'addCompany'])->name('company.addCompany');
    Route::any('addEditCompany', [CompanyController::class, 'addEditCompany'])->name('company.addEditCompany');
    Route::get('company_data', [CompanyController::class, 'data'])->name('company.data');
    Route::any('editCompany', [CompanyController::class, 'editCompany'])->name('company.editCompany');
    Route::any('deleteCompany/{id}', [CompanyController::class, 'deleteCompany'])->name('company.deleteCompany');
});

CODEBASE/routes/web.php
<?php

use App\Http\Controllers\TestingContraoller;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', function () {
	// if(Auth::check())
	// 	Auth::logout();
    return view('welcome');
});

// Route::get('testing',[TestingContraoller::class,'maileView']);

CODEBASE/resources/views/admin/components/application_nave.blade.php
<div class="row" >
    <div class="col-md-8 col-lg-9" >
        <ul class="nav nav-pills tabs-pages tab-leftside">
            <li class="nav-item">
                <a class="nav-link @if($tabeActive=='quick_view') active @endif" href="{{route('admin.application.quickview',$application)}}">
                    <span class="bs-stepper-box">
                        <i data-feather="eye" class="font-medium-3"></i>
                    </span>Quick view </a>
            </li>
            <li class="nav-item">
                <a class="nav-link @if($tabeActive=='application') active @endif " href="{{route('admin.application.application',$application)}}">
                    <span class="bs-stepper-box">
                        <i data-feather="file-text" class="font-medium-3"></i>
                    </span>Application </a>
            </li>
                <li class="nav-item">
                <a class="nav-link @if($tabeActive=='payments') active @endif " href="{{route('admin.application.payments',$application)}}">
                    <span class="bs-stepper-box">
                        <i class="fal fa-money-bill" class="font-medium-3"></i>
                    </span>Payments </a>
            </li>
            @if ($application->status==1 || $application->status>2)
                @if ($application->checkPrePayment())
                    <li class="nav-item">
                        <a class="nav-link @if($tabeActive=='listplants') active @endif " href="{{route('admin.application.listplants',$application)}}">
                            <span class="bs-stepper-box">
                            <i data-feather='list'  class="font-medium-3"></i>
                            </span>List of plants  </a>
                    </li>
                @endif

                @if ($application->final_documents->count())
                    <li class="nav-item">
                        <a class="nav-link @if($tabeActive=='reg_doc') active @endif " href="{{route('admin.application.registion.doc',$application)}}">
                            <span class="bs-stepper-box">
                            <i data-feather='file-text'  class="font-medium-3"></i>
                            </span>Registration Document</a>
                    </li>
                @endif

                @if($application->assignPlants->count())

                <li class="nav-item">
                    <a class="nav-link @if($tabeActive=='technical') active @endif " href="{{route('admin.application.technical',$application)}}">
                        <span class="bs-stepper-box">
                        <i data-feather='file-text'  class="font-medium-3"></i>
                        </span>Technical Assessment</a>
                </li>
                @if($application->assignPlants->count())
                <li class="nav-item">
                    <a class="nav-link @if($tabeActive=='onsite_assessment') active @endif " href="{{route('admin.application.onsite_assessment',$application)}}">
                        <span class="bs-stepper-box">
                            <i class='fal fa-images' class="font-medium-3"></i>
                        </span>Onsite Documents </a>
                </li>
                @endif
                <li class="nav-item">
                    <a class="nav-link @if($tabeActive=='financial') active @endif " href="{{route('admin.application.financial',$application)}}">
                        <span class="bs-stepper-box">
                        <i data-feather='file-text'  class="font-medium-3"></i>
                        </span>Financial Assessment</a>
                </li>
                @endif
                @php
                $fin_accept = \App\Models\FinancialAssessment::where('application_id',$application->id)->count();
                $tec_accept = \App\Models\TechnicalAssessment::where('application_id',$application->id)->count();
                @endphp
                @if($fin_accept>0 && $tec_accept>0)
                <li class="nav-item">
                    <a class="nav-link @if($tabeActive=='jury') active @endif " href="{{route('admin.application.jury',$application)}}">
                        <span class="bs-stepper-box">
                            <i class='fal fa-images' class="font-medium-3"></i>
                        </span>Jury Review</a>
                </li>
                @endif
                @if($application->jury_tech_score && $application->adv_tech_score)
                <li class="nav-item">
                    <a class="nav-link @if($tabeActive=='certificateview') active @endif " href="{{route('admin.application.certificateview',$application)}}">
                        <span class="bs-stepper-box">
                        <i class="fal fa-file-certificate"></i>
                        </span>Certificate View </a>
                </li>
                @endif
            @endif
        </ul>
    </div>
    <div class="col-md-4 col-lg-3" >
        <p class="p-0 m-0 text-bold text-primary" style="font-size: 1rem;"><strong>Vendor Name:<span> {{$application->vendor->name}}  </strong></span>
        <p class="p-0 m-0 text-bold text-primary" style="font-size: 1rem;"><strong>Application Number:<span> {{($application->application_no==null)?'N/A':$application->application_no}}  </strong></span>
        <p class="p-0 m-0 text-bold text-primary" style="font-size: 1rem;"><strong>CII Reference:<span> {{($application->cii_ref_no==null)?'N/A':$application->cii_ref_no}}   </strong></span>
    </div>
</div>

CODEBASE/resources/views/admin/components/footer.blade.php
<!-- BEGIN: Footer-->
<button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>
<footer class="footer footer-static footer-light">
    <p class="clearfix mb-0 font-small-4"><span class="float-md-left d-block d-md-block mt-25">COPYRIGHT &copy; {{date('Y')}}<a class="ml-25" href="https://mirakitech.com" target="_blank">Miraki Technologies</a><span class="d-none d-sm-inline-block">, All rights Reserved</span></span></p>
</footer>

CODEBASE/resources/views/admin/components/header.blade.php
<nav class="header-navbar navbar navbar-expand-lg align-items-center navbar-light navbar-shadow fixed-top">
    <div class="navbar-container d-flex content">
        <ul class="nav navbar-nav align-items-center">
            <li class="nav-item d-none d-lg-block">
                <a class="nav-link nav-link-expand"><i class="ficon" data-feather="maximize"></i></a>
            </li>
        </ul>
        <ul class="nav navbar-nav align-items-center ml-auto">
            {{-- <li class="nav-item dropdown dropdown-notification mr-25">
                <a class="nav-link" href="javascript:void(0);" data-toggle="dropdown"><i class="ficon" data-feather="bell"></i><span class="badge badge-pill badge-danger badge-up">5</span></a>
                <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                    <li class="dropdown-menu-header">
                        <div class="dropdown-header d-flex">
                            <h4 class="notification-title mb-0 mr-auto">Notifications</h4>
                            <div class="badge badge-pill badge-light-primary">6 New</div>
                        </div>
                    </li>
                    <li class="scrollable-container media-list">
                        <a class="d-flex" href="javascript:void(0)">
                            <div class="media d-flex align-items-start">
                                <div class="media-left">
                                    <div class="avatar"><img src="{{ url('/app-assets/images/avatars/avatar-s-11.jpg') }}" alt="avatar" width="32" height="32"></div>
                                </div>
                                <div class="media-body">
                                    <p class="media-heading"><span class="font-weight-bolder">Congratulation Sam 🎉</span>winner!</p>
                                    <small class="notification-text"> Won the monthly best seller badge.</small>
                                </div>
                            </div>
                        </a>
                        <a class="d-flex" href="javascript:void(0)">
                            <div class="media d-flex align-items-start">
                                <div class="media-left">
                                    <div class="avatar"><img src="{{ url('app-assets/images/avatars/avatar-s-11.jpg') }}" alt="avatar" width="32" height="32"></div>
                                </div>
                                <div class="media-body">
                                    <p class="media-heading"><span class="font-weight-bolder">New message</span>&nbsp;received</p>
                                    <small class="notification-text"> You have 10 unread messages</small>
                                </div>
                            </div>
                        </a>
                        <a class="d-flex" href="javascript:void(0)">
                            <div class="media d-flex align-items-start">
                                <div class="media-left">
                                    <div class="avatar bg-light-danger">
                                        <div class="avatar-content">MD</div>
                                    </div>
                                </div>
                                <div class="media-body">
                                    <p class="media-heading"><span class="font-weight-bolder">Revised Order 👋</span>&nbsp;checkout</p>
                                    <small class="notification-text"> MD Inc. order updated</small>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-menu-footer"><a class="btn btn-primary btn-block" href="../support/notifications.html">Read all notifications</a></li>
                </ul>
            </li> --}}
            @php
                
                $str=Auth::user()->name;
                if(!$str)
                    $str = 'A';
                $strA = explode(' ', $str);
                $string = "";
                foreach($strA as $words)
                {
                    $string = $string . $words[0];
                }

            @endphp

            <li class="nav-item dropdown dropdown-user">
                <a class="nav-link dropdown-toggle dropdown-user-link" id="dropdown-user" href="javascript:void(0);" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="user-nav d-sm-flex d-none"><span class="font-medium-2 user-name font-weight-bolder">{{Auth::user()->name}}</span><span class="user-status font-small-2">Admin</span></div>
                    <!-- <span class="avatar"><img class="round" src="{{url('app-assets/images/avatars/profile.png')}}" alt="avatar" height="40" width="40"><span class="avatar-status-online"></span></span> -->
                    <span class="avatar"><div class="circle">{{strtoupper($string)}}</div><span class="avatar-status-online"></span></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-user">
                    <a class="dropdown-item {{($pageTitle=='Profile')?'active':''}}" href="{{route('admin.profile')}}"><i class="mr-50" data-feather="user"></i> Profile</a>
                    <a class="dropdown-item {{($pageTitle=='Change Password')?'active':''}} " href="{{route('admin.changePasswordPage')}}"><i class="mr-50" data-feather="unlock"></i> Change Password</a>
                    <a class="dropdown-item" href="{{route('admin.logout')}}"><i class="mr-50" data-feather="power"></i> Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<div class="nav-header">
    <a href="{{route('admin.dashboard')}}" class="brand-logo pb-1 pt-1 pl-1 pr-1">
        <img class="img-fluid" src="{{url('app-assets/images/logo/logo-white1.png')}}" alt="Login V2">
        
    </a>
    <div class="nav-control">
        <div class="hamburger">
            <span class="line"></span><span class="line"></span><span class="line"></span>
        </div>
    </div>
</div>

CODEBASE/resources/views/admin/components/sidemenu.blade.php
<div class="deznav">
    <div class="deznav-scroll">
        <ul class="metismenu" id="menu">
            <li class="{{($activeMenu=='dashboard')?'active':''}}"><a class="ai-icon"  href="{{route('admin.dashboard')}}" aria-expanded="false">
                <i data-feather="airplay"></i><span class="menu-title " data-i18n="Dashboards"> Dashboard </span></a>
            </li>
            <li class="{{($activeMenu=='assessor')?'active':''}}"><a class="ai-icon" href="{{route('admin.assessors.index')}}" aria-expanded="false">
                <i class="fal fa-users pr-0"></i><span class="menu-title " data-i18n="Invoice">  Assessor Management </span></a>
            </li>
            <li class="{{($activeMenu=='company')?'active':''}}"><a class="ai-icon" href="{{route('admin.company.index')}}" aria-expanded="false">
                <i class="fal fa-id-card pr-0"></i><span class="menu-title " data-i18n="Invoice">  Company Management </span></a>
            </li>
            <li class="{{($activeMenu=='consultant')?'active':''}}"><a class="ai-icon" href="{{route('admin.consultant.index')}}" aria-expanded="false">
                <i class="fal fa-id-card pr-0"></i><span class="menu-title " data-i18n="Invoice">  Facilitator Management </span></a>
            </li>
        </ul>
    </div>
</div>